FROM apache/airflow:2.10.2-python3.10

USER airflow

# copy code files
COPY app /opt/airflow/app
COPY dags /opt/airflow/dags
COPY app/requirements.txt /requirements.txt

# install requirements
RUN pip install --no-cache-dir -r /requirements.txt

# ensure the correct version of airflow is installed
RUN pip install --upgrade --no-cache-dir 'apache-airflow[postgres]==2.10.2'