FROM apache/airflow:2.10.2-python3.10

USER root
# copy code files
COPY app /opt/airflow/app
COPY dags /opt/airflow/dags
COPY app/requirements.txt /requirements.txt

USER airflow
# install requirements
RUN pip install --no-cache-dir -r /requirements.txt